- name: db server configuration
  hosts:  db
  become: yes
  vars:
    dbhost: db.expensesnote.site
  vars_prompt:
    name: mysql_password
    prompt: please enter mysql password
  tasks:  
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql-server
        state:  latest
    - name: Start and enable mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled:  yes
    - name: pip module to install pymysql
      ansible.builtin.pip:
        name: pymysql
        state:  present

    #check root password is set or not
    - name: connect to db using root
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{mysql_password}}"
        login_host: "{{dbhost}}"
        filter: databases
      ignore_errors:  yes
      register: mysql_connection_output

    - name: print mysql connection output
      ansible.builtin.debug:
        msg:  "output:{{mysql_connection_output}}"

    - name: set root password
      ansible.builtin.command:  mysql_secure_installation -uroot -p{{mysql_password}}
      when: mysql_connection_output.failed is true #boolean datatyep