- name: db server configuration
  hosts:  db
  become: yes
  tasks:  
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql-server
        state:  latest
    - name: Start and enable mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled:  yes
    #check root password is set or not
    - name: connect to db using root
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpensesApp@1
        login_host: db.expensesnote.site
        filter: databases