- name: db server configuration
  hosts:  db
  become: yes
  vars:
    dbhost: db.expensesnote.site
  vars_prompt:
    name: mysql_password
    prompt: please enter mysql password
  tasks:  
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql-server
        state:  latest
    - name: Start and enable mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled:  yes
    - name: pip module to install pymysql
      ansible.builtin.pip:
        name: pymysql
        state:  present

    #check root password is set or not
    - name: connect to db using root
      community.mysql.mysql_info:
        login_user: root
        login_password: {{mysql_password}}
        login_host: {{dbhost}}
        filter: databases
      ignore_errors:  yes
      register: userinfo

    - name: print userinfo
      ansible.builtin.debug:
        msg:  "userinfo:{{userinfo}}"