- name: db server configuration
  hosts:  db
  become: yes
  tasks:  
    - name: install mysql
      ansible.builtin.dnf:
        name: mysql
        state:  latest
    - name: Start mysql service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled:  yes